name: "Label bot"
on:
 - pull_request_target

jobs:
  label-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
      - name: Add labels
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler.yml"
          dot: true
      - name: Install PyGithub
        run: |
          pip3 install PyGithub
      - name: Check deadline
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{github.event.number}}
        run: |
          python3 .github/deadline.py
